### ISSUE TITLE
Deprecated package names

### ISSUE THREAD

**Issue by avronr** [smc/swanalekha#2]
In the Swanlekha website, the installation instructions for Debian and Ubuntu ask you to install two packages namely `ibus-gtk3` and `m17n-contrib`.

`ibus-gtk3` points to the `ibus` package itself in Debian.  [https://tracker.debian.org/pkg/ibus-gtk3](https://tracker.debian.org/pkg/ibus-gtk3)
`m17n-contrib` points to `m17n-db` in Debian. [https://tracker.debian.org/pkg/m17n-contrib
](https://tracker.debian.org/pkg/m17n-contrib)

In Ubuntu `ibus-gtk3`'s source package is `ibus` itself. https://packages.ubuntu.com/focal/ibus-gtk3
There's no `m17n-contrib` in the new versions for Ubuntu there is only `m17n-db`. https://packages.ubuntu.com/search?keywords=m17n-contrib&searchon=names

Do we update these or is there a legacy support rabbit hole behind this seemingly simple problem?
If there is no other issue I'd be happy to open a PR with necessary changes.

**Comment by santhoshtr** [comment]
You are correct about the depreacted package names. A user with Ubuntu 20.4 recently told me the same complaint. I think we need to update the documentation to reflect the latest version. But at the sametime, there are lot of people with old distro versions too. So we will need to retain old instructions.

Would you like to open a PR with these documentation updates? Thanks in advance

**Comment by avronr** [comment]
Sure! I'll also try and add instructions for other distros also. I'm not sure if the configuration part will work everywhere though.
